### ISSUE TITLE
Encoding support

### ISSUE THREAD

**Issue by layerqa** [WardPearce/aioquery#3]
Hi, will there be **encoding** support?
[No encoding](https://prnt.sc/ujpzn6) ----> [Encoding **UTF-8**](https://prnt.sc/ujpzau)

**Comment by WardPearce** [comment]
Good catch
https://github.com/WardPearce/aioquery/commit/37ade2a7e2f989e2342b2650b8f2f0083fe41ede (1.1.1)

I also added UTF-8 encoding to the host name

**Comment by layerqa** [comment]
> Хороший улов
> [37ade2a](https://github.com/WardPearce/aioquery/commit/37ade2a7e2f989e2342b2650b8f2f0083fe41ede) (1.1.1)
> 
> Я также добавил кодировку UTF-8 к имени хоста

Ok, thanks, it remains to make an encoding for the players' nicknames

**Comment by WardPearce** [comment]
Ensure you have `aioquery==1.1.1` installed.

Names are encoded correctly with `1.1.1`
https://github.com/WardPearce/aioquery/blob/master/aioquery/models.py#L18

**Comment by layerqa** [comment]
Name: aioquery
Version: 1.1.1
Summary: Asynchronous source A2S.
Home-page: https://aioquery.readthedocs.io/en/latest/
Author: WardPearce
Author-email: wardpearce@protonmail.com
License: Apache-2.0 License
Location: c:\users\usfvo\appdata\local\programs\python\python38-32\lib\site-packages
Requires: sphinxcontrib-trio, asyncio-dgram, asynctest
Required-by:

Encoding is not fixed the player with the name Аиквери is not displayed correctly
Check my fork

**Comment by WardPearce** [comment]
Open a PR
